### ISSUE TITLE
a issue in readme

### ISSUE THREAD

**Issue by Rivsen** [event-band/band-symfony-application#1]
when create project using composer, we need an option: --stability="dev", so the create command will be:

```bash
$ php composer.phar create-project --stability="dev" "event-band/band-symfony-application" event-band "~1.0.0@dev"
```

**Comment by korotovsky** [comment]
I'll update README.md soon. Thanks!

**Comment by Rivsen** [comment]
Thank you for making these awesome tools. :-)

**Comment by korotovsky** [comment]
@Rivsen We are planning to release `2.0` version soon, and it would be nice to get feedback from you to make `2.0` better, if you use [event-band](https://github.com/event-band) in production.

**Comment by Rivsen** [comment]
@korotovsky Yes I will and I'm looking for a async event framework based on the symfony2's Event Dispatcher, this one is very match. :dancers:

**Comment by korotovsky** [comment]
@Rivsen Great! Let me know if you have any questions.

**Comment by Rivsen** [comment]
Yes, I will. ;-)
